---
title: "Research Projects"
description-meta: "Research projects by Yuan Liao"
title-block-banner: false
---

## Social Segregation Revealed by Big Mobility Data

*Funded by the Swedish Research Council (No. 2022-06215)*

This [project](https://research.chalmers.se/project/11137) aims to use big data on human mobility to better understand social segregation in cities. The project will use advanced techniques to study how social segregation is affected by mobility, the built environment, and residence characteristics in different regions, to support effective policies and urban planning that promote diversity and address inequality issues.

The research project aims to provide new insights into social segregation and support policies that go beyond the boundaries of residential areas. The significance and scientific novelty lie in the below two aspects:

1) Profound insights into how experienced social segregation distributes in global regions at an unprecedentedly high spatiotemporal resolution, a big step forward beyond our understanding of residential segregation;

2) Innovative explanations of social segregation by built environment, mobility behaviours, and housing, which can be used to make effective place-based policies and transport planning to mitigate segregation and inequalities in today's urban systems.

This three-year project is managed and implemented by Dr. Yuan Liao with Chalmers University of Technology, Sweden, and Technical University of Denmark. Collaborators include:

- Dr. Sonia Yeh, Chalmers University of Technology, Sweden
- Dr. Jorge Gil, Chalmers University of Technology, Sweden
- Dr. Laura Alessandretti, Technical University of Denmark
- Dr. Rafael H. M. Pereira, Institute for Applied Economic Research (Ipea), Brazil

We make all studies open-source on our [GitHub page](https://github.com/MobiSegInsights).

---

## Sustainable Cities

*Understanding human mobility with big data*

This [proposal](https://research.chalmers.se/en/project/7500) is organized around two big ideas:

1) Explore the potential expressive analysis of the continuous and large amounts of information sensed in urban environments can boost the understanding of human mobility patterns in urban cities;

2) Enhance access data and knowledge to citizens, stakeholders and researchers to improve their ability to utilize live information that will help achieve social, economic and environmental sustainability in cities.

Two projects were conducted: exploring the validity and analytical strength of using geotagged social media data for understanding urban activity and mobility pattern, and leveraging state-of-the-art analytics to observe, alert, predict and share live congestion information associated with traffic incidents in urban cities.

---

## User Experience of Driver-Vehicle Interaction Systems

*2016-2017 at Chalmers University of Technology*

This project explores the human-factor issues of designing advanced driver assistance systems: enhancing intelligence, comfort, and safety.

The studies were conducted at the [Division of Interaction Design](https://www.chalmers.se/en/departments/cse/organisation/id/Pages/default.aspx), Chalmers University of Technology.

---

## Driver Behaviours

*2014-2019 at Tsinghua University and Chalmers*

This project uses empirical data, either from naturalistic driving or simulator experiments, to understand driver behaviours and apply the obtained knowledge to enhance driving safety, comfort, and intelligence.

It covers the studies since my master's study in 2014-2016 at the [iDLAB](http://www.idlab-tsinghua.com/thulab/labweb/index.html), Tsinghua University, as well as followed efforts in 2016-2019 during my PhD study.

{{< include /files/includes/_socialshare.qmd >}}
